# Import libraries

In [18]:
import pandas as pd
import sklearn as sk
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import f1_score, precision_score, recall_score
import pickle
import json

# Import Data

In [3]:
X_train = pd.read_csv(r"/home/sd-work/Code/Minor-Project/Preprocessed/X_train.csv")
y_train = pd.read_csv(r"/home/sd-work/Code/Minor-Project/Preprocessed/y_train.csv")
X_test = pd.read_csv(r"/home/sd-work/Code/Minor-Project/Preprocessed/X_test.csv")
y_test = pd.read_csv(r"/home/sd-work/Code/Minor-Project/Preprocessed/y_test.csv")

# Training the model

In [3]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

/home/sd-work/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/sd-work/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

# Preduction on test set

In [8]:
y_pred = classifier.predict(X_test)

# Evaluation

In [9]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

#[[1782890  199791]
# [ 215147 1766811]]




[[1782890  199791]
 [ 215147 1766811]]


In [20]:
f1 = f1_score(y_test, y_pred, average=None)
# array([0.89576303, 0.8949141 ])

In [15]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)
# 0.8953402819273079

0.8953402819273079


In [16]:
recall = recall_score(y_test, y_pred)
print(recall)
# 0.8914472456025809

0.8914472456025809


In [17]:
precision = precision_score(y_test, y_pred)
print(precision)
# 0.8984080154499996

0.8984080154499996


In [26]:
metrics = {
    "confusion_matrix" : cm.tolist(),
    "f1_score" : f1.tolist(),
    "accuracy" : accuracy,
    "recall" : recall,
    "precision" : precision
}

with open('/home/sd-work/Code/Minor-Project/Metrics/LR.json', 'w') as fp:
    json.dump(metrics, fp)

In [7]:
pickle.dump(classifier, open("/home/sd-work/Code/Minor-Project/Models/Logistic_Regression.sav", 'wb'))